"""Added passenger details

Revision ID: 74b3286cf3de
Revises: 92705eb1bbe0
Create Date: 2026-06-30 18:54:29.958905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b3286cf3de'
down_revision = '92705eb1bbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('passenger_age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('passenger_gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('travel_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('travel_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('passenger_gender')
        batch_op.drop_column('passenger_age')
        batch_op.drop_column('passenger_name')

    # ### end Alembic commands ###
