"""Seat Number

Revision ID: 92705eb1bbe0
Revises: 
Create Date: 2026-06-30 18:39:15.226613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92705eb1bbe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('seat_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('seat_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('bus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
